site_name: BabylonML Documentation
site_description: 'Declarative 3D scenes for the web using Babylon.js and HTML.'
repo_name: 'BabylonML'
site_author: 'BabylonML Contributors'

# Define the directory containing your Markdown documentation files
docs_dir: 'docs'

# Navigation structure
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Core Concepts:
    - Scene: concepts/scene.md
    - Entity: concepts/entity.md
    - Components: concepts/components.md
  - Components Reference:
    - Position: components/position.md
    - Rotation: components/rotation.md
    - Scale: components/scale.md
    - Geometry: components/geometry.md
    - Material: components/material.md
    - Camera: components/camera.md
    - Light: components/light.md # Added Light component
    - Animation: components/animation.md # Added Animation component
    - Sound: components/sound.md # Added Sound component
  - Examples:
    - Overview: examples/index.md
    - Basic Scene: examples/basic_scene.md
    - Animation: examples/animation_scene.md
    - AR Scene: examples/ar_scene.md
    - Assets (Planned): examples/assets_scene.md
    - Explicit Cam/Light: examples/explicit_camera_light_placeholder.md
    - Lights: examples/lights_scene.md
    - Mesh Loading: examples/mesh_example.md
    - Multi-Camera: examples/multi_camera_scene.md
    - PBR Material: examples/pbr_material_scene.md
    - Photo Dome: examples/photodome_example.md
    - Sound: examples/sound_scene.md
    - Text (Planned): examples/text_scene.md
    - Video Dome: examples/videodome_example.md
    - VR Scene: examples/vr_scene.md

# Theme configuration (using the default 'mkdocs' theme for now)
theme:
  name: material
  favicon: assets/favicon.ico # Optional: Add a favicon
  features:
    - navigation.instant
    - navigation.tracking
    # - navigation.tabs.sticky # Optional: Makes tabs sticky
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: orange # Or another color like 'blue grey'
      accent: amber # Or another accent

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: navy blue # Or another color
      accent: orange # Or another accent
      
  extra_css:
    - css/custom.css

# Markdown extensions (optional, add features like tables, footnotes, etc.)
# markdown_extensions:
#   - footnotes
#   - attr_list
#   - pymdownx.highlight:
#       anchor_linenums: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences

# Repository URL (optional, adds link to source)
# repo_url: https://github.com/yourusername/babylonml
# repo_name: 'yourusername/babylonml'

# Edit URI (optional, allows users to suggest edits)
# edit_uri: edit/main/docs/

# Copyright (optional)
# copyright: 'Copyright &copy; 2025 Your Name'
